'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const TABS=['Start Here','My Details','Quote','Tax Invoice','Invoice','Variation','Rate Calculator','Line Items','Worked Examples'];
const FOOT='General template for administrative and educational use only. Not legal, tax or WHS advice. Adapt to your business and each job. Have your SWMS reviewed by a qualified WHS professional before use.';
const LISTS={
Electrician:'Labour - licensed electrician|Labour - apprentice|Call-out fee (standard hours)|After-hours or emergency call-out fee|Fault finding and diagnosis|Supply and install double power point (GPO)|Supply and install LED downlight|Supply and install ceiling fan|Supply and install interconnected smoke alarm|Supply and install safety switch (RCD)|Switchboard upgrade (supply and install)|EV charger installation (supply and install)|Data, TV or antenna point|Test and tag (portable appliances)|Materials at cost plus markup|Travel or mobilisation|Compliance paperwork and test results (where required in your state)',
Plumber:'Labour - licensed plumber|Labour - apprentice|Call-out fee (standard hours)|After-hours or emergency call-out fee|Leak detection|Supply and install mixer tap|Replace toilet suite (supply and install)|Hot water system (supply and install)|Remove and dispose of old hot water system|Clear blocked drain|Drain camera inspection|Replace flexible hoses or isolation valves|Pressure limiting or tempering valve (supply and install)|Gas fitting work (licensed gasfitter only)|Materials at cost plus markup|Travel or mobilisation|Permit, inspection or compliance paperwork (where required in your state)',
Other:'Labour - tradesperson|Labour - apprentice or offsider|Call-out fee (standard hours)|After-hours or emergency call-out fee|Quote or site inspection fee|Minimum charge (first hour)|Materials at cost plus markup|Materials supply only|Delivery|Equipment or plant hire|Waste removal and tip fees|Site clean-up|Travel or mobilisation|Progress payment - stage 1|Progress payment - stage 2|Permit, inspection or compliance paperwork (where required in your state)|Other work (describe it)'};
const UN={Electrician:'hour,hour,each,each,hour,each,each,each,each,each,job,job,each,item,lot,each,job',Plumber:'hour,hour,each,each,hour,each,each,each,each,job,job,each,each,hour,lot,each,job',Other:'hour,hour,each,each,each,each,lot,lot,each,day,lot,each,each,stage,stage,job,job'};
const MK='Pick your markup on the Rate Calculator tab.',MH='Your main hourly rate. See the Rate Calculator tab.',CO='Covers travel and the first look.',AH='Say your after-hours times on the quote.',ST_='Check your state rules for where they are required.',NS='Names and rules differ by state.';
const NT={Electrician:{0:MH,2:CO,3:AH,8:ST_,10:'List what is included and what is not.',14:MK,16:'Certificate names and rules differ by state.'},Plumber:{0:MH,2:CO,3:AH,7:'List the model and size.',12:ST_,13:'Only if you hold the licence.',14:MK,16:NS},Other:{0:MH,2:CO,3:AH,4:'Say if it is credited back when the job goes ahead.',6:MK,13:'Describe what the stage covers.',15:NS}};
const EX={Electrician:'Painting, plastering and making good after cable runs (by others).|Asbestos identification, testing or removal.|Repairs to existing wiring found to be unsafe or non-compliant (quoted separately as a variation).|Network provider and council fees, unless listed in this quote.|Work in roof, wall or floor spaces that cannot be safely reached.|Fittings or appliances supplied by the customer (no warranty on supplied items).|Any work not listed in the scope above.',Plumber:'Tiling, plastering, painting and carpentry make-good (by others).|Concrete cutting, excavation and reinstatement.|Asbestos identification, testing or removal.|Hidden or concealed problems found during the work, such as corroded or damaged pipes (quoted separately as a variation).|Permit, inspection and authority fees, unless listed in this quote.|Damage caused by tree roots or ground movement.|Fittings or fixtures supplied by the customer (no warranty on supplied items).',Other:'Painting, plastering and making good (by others).|Asbestos identification, testing or removal.|Hidden or concealed problems found during the work (quoted separately as a variation).|Permit, inspection and authority fees, unless listed in this quote.|Work that cannot be safely reached.|Items supplied by the customer (no warranty on supplied items).|Any work not listed in the scope above.'};
const DEF={'Rate Calculator':{wage:'$90,000.00',costs:'$25,000.00',weeks:'46',hrs:'25',part:'$120.00',mk:'30'},Variation:{pay:'Added to the final invoice',prev:'$0.00'}};
let ST={D:{gst:'Yes',trade:'Electrician',terms:'7',rate:'10'},T:{}},tab='Start Here';
try{const s=JSON.parse(localStorage.getItem('tpk2')||'{}');ST.D={...ST.D,...(s.D||{})};ST.T=s.T||{}}catch(e){}
const save=()=>{try{localStorage.setItem('tpk2',JSON.stringify(ST))}catch(e){}};
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const has=s=>String(s??'').trim()!=='',num=s=>parseFloat(String(s??'').replace(/[$,\s]/g,''))||0;
const r2=n=>Math.round((n+Number.EPSILON)*100)/100;
const usd=n=>(n<0?'-':'')+'$'+Math.abs(n).toLocaleString('en-AU',{minimumFractionDigits:2,maximumFractionDigits:2});
const fmtD=v=>{if(!has(v))return'';const[a,b,c]=v.split('-');return new Date(a,b-1,c).toLocaleDateString('en-AU',{day:'numeric',month:'short',year:'numeric'})};
const addD=(v,n)=>{if(!has(v))return'';const[a,b,c]=v.split('-'),d=new Date(a,b-1,+c+n);return fmtD(d.getFullYear()+'-'+(d.getMonth()+1)+'-'+d.getDate())};
const get=(s,k)=>{const v=s==='D'?ST.D[k]:(ST.T[s]||{})[k];return v!==undefined?v:(DEF[s]||{})[k]};
const put=(s,k,v)=>{if(s==='D')ST.D[k]=v;else(ST.T[s]=ST.T[s]||{})[k]=v;save()};
const reg=()=>ST.D.gst==='Yes',rate=()=>(num(ST.D.rate)||10)/100;

/* ---------- builders ---------- */
function fld(s,k,t,o={}){const a=`data-s="${s}" data-k="${k}" id="i-${k}"`;
 if(t==='a')return`<textarea ${a} rows="1"></textarea>`;
 if(t==='d')return`<div><input type="date" ${a}><div class="dfm" id="c-${k}f"></div></div>`;
 if(t==='s')return`<select ${a}>${o.o.map(x=>`<option>${esc(x)}</option>`).join('')}</select>`;
 if(t==='m')return`<input class="m" inputmode="decimal" placeholder="$0.00" ${a}>`;
 if(t==='n')return`<input inputmode="decimal" ${a}>`;
 if(t==='c')return`<div class="cv" id="c-${k}"></div>`;
 return`<input type="text" ${a} ${o.ph?`placeholder="${esc(o.ph)}"`:''} ${o.auto?`autocomplete="${o.auto}"`:''}>`}
const row=(s,k,l,t,o={})=>`<div class="fr"><label for="i-${k}">${l}</label>${fld(s,k,t,o)}${o.ex?`<div class="ex">${esc(o.ex)}</div>`:''}</div>`;
const sec=t=>`<div class="sec">${t}</div>`;
const band=(t)=>`<div class="band"><b>${esc(ST.D.name||'Your Business Name')}</b><i>${t}</i></div><div class="sub">${['ABN '+(ST.D.abn||'00 000 000 000'),'Licence '+(ST.D.lic||'your licence no.'),ST.D.phone||'phone',ST.D.email||'email'].map(esc).join('   |   ')}</div>`;
function lines(s,withGst,head,n=8){let h=`<div class="ln th ${withGst?'':'ni'}"><span>#</span><span>${head[0]}</span><span>Qty</span><span>${head[1]}</span>${withGst?'<span>GST on item?</span>':''}<span>${head[2]}</span></div>`;
 for(let i=1;i<=n;i++)h+=`<div class="ln ${withGst?'':'ni'}"><span class="nn">${i}</span><input class="d" list="dl" placeholder="Description" data-s="${s}" data-k="d${i}"><input class="q" inputmode="decimal" placeholder="Qty" data-s="${s}" data-k="q${i}"><input class="p m" inputmode="decimal" placeholder="$0.00" data-s="${s}" data-k="p${i}">${withGst?`<select data-s="${s}" data-k="g${i}"><option>Yes</option><option>No</option></select>`:''}<div class="am" id="c-a${i}"></div></div>`;return h}
const tr=(l,id,cls='')=>`<div class="tr ${cls}"><span id="${id}l">${l}</span><span id="${id}"></span></div>`;
const payBlock=`${sec('PAYMENT DETAILS')}<div class="pay" id="c-pay1"></div><div class="pay" id="c-pay2"></div>`;
const btns=`<div class="btns"><button class="b o" id="pdf">Save as PDF</button><button class="b g" id="clr">Clear this document</button></div><div class="note">Save as PDF: tap the button, then choose Save as PDF as the printer. Your work is saved on this device only.</div>`;

function view(){
 if(tab==='Start Here'){const st=[['1','Open My Details. Type your business name, ABN, trade, bank name, BSB and account number in the cream boxes. You only do this once.'],['2','Not sure if you charge GST? Pick Yes or No on My Details. Yes = use Tax Invoice. No = use Invoice. The page warns you if you pick the wrong tab.'],['3','Every new job: open Quote, Tax Invoice or Invoice and type over the cream boxes. The sums work themselves out. The Description box suggests common jobs for your trade. Type your own words any time.'],['4','Dates: pick them from the calendar. The due date is worked out for you.'],['5','Send it: tap Save as PDF at the bottom of the document, then Clear this document for the next job.'],['6','Customer wants to pay by card? Paste your card reader or payment link on My Details. Never write card numbers on a quote or invoice, and never ask for them by text or email.']];
  return`<div class="pg"><div class="band"><b>TRADIE PAPERWORK KIT</b></div><div class="sub">Start here. Set up in 3 minutes.</div>${sec('SET UP AND USE')}${st.map(x=>`<div class="st"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}${sec('WHICH TAB DO I USE?')}<div class="note">Quote: price a job before you start. Tax Invoice: registered for GST, use this to get paid. Invoice: not registered for GST, use this to get paid. Variation: customer wants extra work or something changes, get it approved first. Rate Calculator: work out your hourly rate and a fair markup on parts. Line Items: pick-list of common jobs for your trade. Worked Examples: see a finished quote and invoice.</div>${sec('WHAT THIS KIT FOLLOWS')}<div class="note">The Tax Invoice tab covers the 7 details the ATO lists for tax invoices, plus the extra buyer name or ABN for sales of $1,000 or more. Checked against the ATO "Tax invoices" page (ato.gov.au), last updated 18 September 2026. Not approved or endorsed by the ATO. Rules change, so check the ATO page for anything new.</div><div class="note">Your details stay on this device. Nothing you type is sent to anyone. Questions? Reply to your receipt email and I will answer within 24 hours.</div><div class="note">${FOOT}</div></div>`}
 if(tab==='My Details'){return`<div class="pg"><div class="band"><b>MY BUSINESS DETAILS</b></div><div class="sub">Fill this page in once. It appears on the Quote, Tax Invoice and Invoice tabs by itself.</div>
  ${sec('YOUR BUSINESS')}${row('D','name','Business name','t',{ex:'Smith Electrical',auto:'organization'})}${row('D','abn','ABN (11 digits)','t',{ex:'12 345 678 901'})}${row('D','lic','Licence no. (if you have one)','t',{ex:'EC12345'})}${row('D','phone','Phone','t',{ex:'0412 345 678',auto:'tel'})}${row('D','email','Email','t',{ex:'jo@smithelectrical.com.au',auto:'email'})}
  ${row('D','gst','Registered for GST?','s',{o:['Yes','No'],ex:'Many sole traders under $75,000 a year are not registered. Check the ATO.'})}${row('D','trade','Your trade','s',{o:['Electrician','Plumber','Other'],ex:'Decides which job suggestions show in the Description boxes.'})}
  ${sec('GETTING PAID')}${row('D','bank','Bank name','t',{ex:'Commonwealth Bank'})}${row('D','acct','Bank account name','t',{ex:'Smith Electrical'})}${row('D','bsb','BSB','t',{ex:'062-000'})}${row('D','acno','Account number','t',{ex:'12345678'})}${row('D','payid','PayID (optional)','t',{ex:'0412 345 678'})}${row('D','card','Card payment link (optional)','t',{ex:'Paste the payment link from your card reader or provider. Never type card numbers here or on an invoice.'})}${row('D','terms','Payment terms (days)','n',{ex:'7'})}${row('D','rate','GST rate (%)','n',{ex:'10% (Australian GST. Only change it if the law changes.)'})}
  <div class="note">The 10% rate is Australian GST. Your Registered for GST answer decides whether the Quote shows GST and which invoice tab to use: Tax Invoice if Yes, Invoice if No.</div><div class="note">${FOOT}</div></div>`}
 if(tab==='Variation'){const Y=true;return`<div class="pg">${band('VARIATION')}<div class="leg">Type in the cream boxes. Everything else works itself out. Get this approved BEFORE you do the extra work.</div>${sec('VARIATION DETAILS')}${row(tab,'no','Variation no.','t')}${row(tab,'date','Date','d')}${row(tab,'qno','Quote / job no.','t')}${row(tab,'days','Extra days','n')}${row(tab,'cust','Customer','t',{auto:'name'})}${row(tab,'site','Job site','t')}${row(tab,'why','Why the change?','s',{o:['Customer asked for it','Hidden problem found','Rule or compliance change','Material or supplier change','Other']})}${sec('WHAT IS CHANGING')}${row(tab,'desc','Describe the change','a')}<div style="height:8px"></div>${lines(tab,Y,['Description','Unit price (ex GST)','Amount (ex GST)'],4)}${tr('Subtotal (ex GST)','t1')}${tr('GST','t3')}${tr('THIS VARIATION (extra cost)','t4','big')}${sec('NEW CONTRACT TOTAL')}${row(tab,'orig','Original quote total','m',{ex:'Leave blank to use the total from your Quote tab. Type a figure if this job was quoted somewhere else.'})}${row(tab,'prev','Earlier approved variations on this job ($)','m')}${tr('This variation','v3')}${tr('NEW TOTAL','v4','big')}<div class="note">Working on a second variation? Put the earlier approved ones in the box above.</div>${row(tab,'pay','How it gets paid','t')}<div class="note">On domestic building work most states have strict rules for variations (written, signed, sometimes extra steps). Check your state regulator before you rely on this form. This is not legal advice.</div>${sec('CUSTOMER APPROVAL')}<div class="note" style="color:var(--navy);font-weight:700;font-size:13px">I approve this variation, the extra cost and any extra days shown above. The extra work starts after I approve.</div>${row(tab,'an','Name','t')}${row(tab,'as','Signature','t')}${row(tab,'ad','Date','d')}${btns}<div class="note">${FOOT}</div></div>`}
 if(tab==='Rate Calculator'){return`<div class="pg"><div class="band"><b>RATE AND MARKUP CALCULATOR</b></div><div class="leg">Work out what to charge so jobs actually pay. The cream boxes hold EXAMPLE numbers: type over them with yours. All prices are ex GST.</div>${sec('1. YOUR MINIMUM HOURLY RATE')}${row(tab,'wage','Wage you want before tax ($ a year)','m',{ex:'Example only. What you want to take home before tax. Ask your accountant how much to set aside for tax and super.'})}${row(tab,'costs','Business costs ($ a year)','m',{ex:'Example only. Vehicle, fuel, insurance, tools, phone, licence, accountant, software, training.'})}${row(tab,'weeks','Weeks you work a year','n',{ex:'Example only. Take out holidays, public holidays, sick days and quiet weeks.'})}${row(tab,'hrs','Chargeable hours a week','n',{ex:'Example only. Quoting, driving, buying parts and paperwork usually eat a big part of the week, so this is lower than hours worked.'})}${row(tab,'need','Money you need to bring in ($ a year)','c',{ex:'Wage plus business costs.'})}${row(tab,'hy','Chargeable hours a year','c',{ex:'Weeks times chargeable hours.'})}${tr('MINIMUM HOURLY RATE (ex GST)','rt','big')}<div class="note">Charge at least this. Less than this and you are working for less than you planned.</div>${row(tab,'rg','Same rate including GST','c',{ex:'Only adds GST if you said you are registered on My Details.'})}${sec('2. MATERIALS MARKUP')}${row(tab,'part','What you pay for the part ($)','m',{ex:'Example only. Your cost price, ex GST.'})}${row(tab,'mk','Markup you add (%)','n',{ex:'Example only. Markup is a percentage added ON TOP of what you paid.'})}${row(tab,'sp','Sell price (ex GST)','c',{ex:'What you charge the customer for the part.'})}${row(tab,'pf','Profit on the part ($)','c',{ex:'Sell price minus what you paid.'})}${row(tab,'mg','Margin (profit as % of sell price)','c',{ex:'Markup and margin are different. A 30% markup is only about a 23% margin.'})}${sec('3. WHAT EACH MARKUP REALLY EARNS')}${[10,15,20,25,30,40,50].map(m=>`<div class="tr" style="font-weight:400"><span>${m}% markup</span><span>${(m/(100+m)*100).toFixed(1)}% margin</span></div>`).join('')}<div class="note">If you want to keep a set margin on parts, check this table first. To keep a 25% margin you need a 33% markup, not 25%.</div><div class="note">A starting point only. Check what other trades near you charge and talk to your accountant. Numbers above are examples, not advice.</div><div class="note">${FOOT}</div></div>`}
 if(tab==='Line Items'){const T=ST.D.trade||'Electrician',it=LISTS[T].split('|'),un=UN[T].split(','),nt=NT[T]||{};return`<div class="pg"><div class="band"><b>${T.toUpperCase()} LINE ITEMS</b></div><div class="leg">Tap a Description box on the Quote, Tax Invoice, Invoice or Variation tab to pick from this list, or just type your own words. Prices are blank on purpose: set your own. To change this list, change "Your trade" on My Details.</div>${sec('COMMON LINE ITEMS')}${it.map((d,i)=>`<div class="tr" style="font-weight:400;border-bottom:1px solid var(--line)"><span>${esc(d)}${nt[i]?`<br><small style="color:var(--mut)">${esc(nt[i])}</small>`:''}</span><span style="color:var(--mut)">${un[i]}</span></div>`).join('')}${sec('SUGGESTED EXCLUSIONS (copy what applies into the Exclusions box on your Quote)')}${EX[T].split('|').map(x=>`<div class="note" style="color:#1f2937;font-size:13px">&bull; ${esc(x)}</div>`).join('')}<div class="note">Starter wording only. Change it to suit your trade, your state and each job.</div><div class="note">${FOOT}</div></div>`}
 if(tab==='Worked Examples'){const ln=(a,b)=>`<div class="tr" style="font-weight:400;border-bottom:1px solid var(--line)"><span>${a}</span><span>${b}</span></div>`;return`<div class="pg"><div class="band"><b>WORKED EXAMPLES</b></div><div class="leg">EXAMPLES ONLY. The names and figures are made up to show what a finished quote and invoice look like. Set your own rates.</div>${sec('EXAMPLE A: SPARKY QUOTE (Q-001)')}<div class="note" style="color:#1f2937">Replace 6 downlights in living room. Prices exclude GST.</div>${ln('1. Labour (hours) &nbsp; 3 &times; $95.00 &nbsp; GST: Yes','$285.00')}${ln('2. LED downlights &nbsp; 6 &times; $30.00 &nbsp; GST: Yes','$180.00')}${tr('Subtotal (ex GST)','x1').replace('<span id="x1"></span>','<span>$465.00</span>')}${tr('GST (10%)','x2').replace('<span id="x2"></span>','<span>$46.50</span>')}<div class="tr big"><span>TOTAL</span><span>$511.50</span></div><div class="note">No deposit for a job this size. Balance due on completion. Exclusions: plastering and painting.</div>${sec('EXAMPLE B: PLUMBER TAX INVOICE (INV-014)')}<div class="note" style="color:#1f2937">Replace kitchen mixer tap. Bill to: A. Customer.</div>${ln('1. Labour (hours) &nbsp; 1.5 &times; $110.00 &nbsp; GST: Yes','$165.00')}${ln('2. Mixer tap supplied &nbsp; 1 &times; $120.00 &nbsp; GST: Yes','$120.00')}<div class="tr"><span>Subtotal (ex GST)</span><span>$285.00</span></div><div class="tr"><span>GST (10%)</span><span>$28.50</span></div><div class="tr big"><span>TOTAL PAYABLE (incl GST)</span><span>$313.50</span></div><div class="note">Total price includes GST of $28.50. Payment due within 7 days.</div><div class="note">To make your own: open the Quote, Tax Invoice or Invoice tab and type in the cream boxes. Tap Clear this document when you are ready for the next job.</div><div class="note">${FOOT}</div></div>`}
 const q=tab==='Quote',ti=tab==='Tax Invoice',title=q?'QUOTE':ti?'TAX INVOICE':'INVOICE';
 let h=`<div class="pg">${band(title)}<div class="leg" id="leg"></div>${sec(q?'QUOTE DETAILS':'INVOICE DETAILS')}`;
 h+=row(tab,'no',q?'Quote no.':'Invoice no.','t')+row(tab,'date',q?'Date':'Issue date','d')+row(tab,'cust',q?'Customer':'Bill to','t',{auto:'name'});
 h+=q?row(tab,'valid','Valid until','c')+row(tab,'phone','Phone / email','t'):row(tab,'due','Due date','c');
 if(ti)h+=row(tab,'cabn','Customer ABN','t');
 h+=row(tab,'addr','Address','t')+row(tab,'site',q?'Job site':'Job address','t');
 if(ti)h+='<div class="warn" id="req"></div>';
 if(q)h+=sec('SCOPE AND PRICE')+row(tab,'scope','Scope of work','a')+row(tab,'ptype','Price type','s',{o:['Fixed price','Estimate (final price based on actual hours and materials)']});
 h+='<div style="height:8px"></div>'+lines(tab,tab!=='Invoice',['Description',q?'Unit price (ex GST)':ti?'Price (ex GST)':'Unit price',q||ti?'Amount (ex GST)':'Amount']);
 if(tab==='Invoice')h+=tr('TOTAL PAYABLE','t4','big')+'<div class="note">GST not applicable. Supplier is not registered for GST.</div>';
 else h+=tr('Subtotal (ex GST)','t1')+tr('GST','t3')+tr(ti?'TOTAL PAYABLE (incl GST)':'TOTAL','t4','big')+'<div class="note" id="c-gn"></div>';
 if(q)h+=sec('TERMS')+row(tab,'incl','Inclusions','a')+row(tab,'excl','Exclusions','a')+row(tab,'dep','Deposit (%)','n')+'<div class="note" id="c-dn"></div>'+row(tab,'bal','Balance due','t')+row(tab,'fee','Quote fee ($)','m')+'<div class="note">Optional. If you charge a quote fee, say it is credited back if the customer goes ahead.</div>';
 h+=payBlock;
 if(q)h+='<div class="note">Variations: any change to the scope of work will be quoted and agreed in writing before the work starts.</div>'+sec('ACCEPTANCE')+'<div class="note"><b>I accept this quote.</b></div>'+row(tab,'an','Name','t')+row(tab,'as','Signature','t')+row(tab,'ad','Date','d');
 else h+=`<div class="pay" id="c-terms"></div>`;
 return h+`${btns}<div class="note">${FOOT}</div></div>`}

/* ---------- live sums and messages ---------- */
const set=(id,t)=>{const e=$('#'+id);if(e)e.textContent=t};
function lc(s,n,show,dom=true){let sub=0,tax=0;for(let i=1;i<=n;i++){const a=has(get(s,'q'+i))&&has(get(s,'p'+i)),v=a?r2(num(get(s,'q'+i))*num(get(s,'p'+i))):0;sub+=v;if(a&&get(s,'g'+i)!=='No')tax+=v;const e=dom&&$('#c-a'+i);if(e){e.textContent=a?usd(v):'';e.parentElement.classList.toggle('empty',![get(s,'d'+i),get(s,'q'+i),get(s,'p'+i)].some(has))}}sub=r2(sub);const g=show?r2(tax*rate()):0;return{sub,g,tot:r2(sub+g)}}
const dates=s=>$$('[id^="c-"][id$="f"]').forEach(e=>{e.textContent=fmtD(get(s,e.id.slice(2,-1)))});
const gl=R=>R?'GST ('+Math.round(rate()*100)+'%)':'GST (not registered, none charged)';
function dc(){const D=ST.D,s=tab,q=s==='Quote',ti=s==='Tax Invoice',R=reg(),show=ti||(q&&R),v=lc(s,8,show),tot=v.tot,no=get(s,'no')||'',dt=get(s,'date');
 set('t1',usd(v.sub));set('t3',show?usd(v.g):'');set('t3l',gl(show));set('t4',usd(tot));dates(s);set('c-valid',addD(dt,30));set('c-due',addD(dt,num(D.terms)));
 let leg='Type in the cream boxes. Everything else works itself out.',bad=false;
 if(ti&&!R){leg='STOP: you are not registered for GST. Use the Invoice tab, not this one.';bad=true}
 if(s==='Invoice'&&R){leg='STOP: you are registered for GST. Use the Tax Invoice tab, not this one.';bad=true}
 const L=$('#leg');if(L){L.textContent=leg;L.className='leg'+(bad?' bad':'')}
 set('req',ti&&tot>=1000&&!has(get(s,'cust'))&&!has(get(s,'cabn'))?'REQUIRED: add the customer name or ABN. The ATO needs it when the total is $1,000 or more including GST.':'');
 if(ti){const f=[1,2,3,4,5,6,7,8].some(i=>get(s,'g'+i)==='No'&&has(get(s,'q'+i))&&has(get(s,'p'+i))&&num(get(s,'q'+i))*num(get(s,'p'+i))>0);set('c-gn',f?'GST amount is shown above. Items marked No are GST-free.':'Total price includes GST of '+usd(v.g))}
 if(q){set('c-gn',R?'All prices exclude GST. GST is added to items marked Yes.':'Not registered for GST. No GST charged.');
  let dp=num(get(s,'dep'));if(dp>1)dp/=100;set('c-dn',has(get(s,'dep'))?'Deposit due: '+usd(r2(tot*dp))+". Check your regulator's current deposit limit for building work before you ask for it.":"Deposits on building work are capped in most states, and the cap depends on the contract value. Check your regulator's current limit before you set a percentage.")}
 $('#c-pay1').innerHTML=`<b>Bank:</b> ${esc(D.bank)}   |   <b>Account name:</b> ${esc(D.acct)}   |   <b>BSB</b> ${esc(D.bsb)}   |   <b>Account no.</b> ${esc(D.acno)}`;
 $('#c-pay2').textContent=(has(D.payid)?'PayID: '+D.payid+'   |   ':'')+(has(D.card)?'Pay by card: '+D.card+'   |   ':'')+'Reference: '+no;
 set('c-terms','Payment due within '+(D.terms||'')+' days of the invoice date.')}
function vc(){const s='Variation',R=reg(),v=lc(s,4,R),qt=lc('Quote',8,R,false).tot,o=has(get(s,'orig'))?num(get(s,'orig')):qt;
 set('t1',usd(v.sub));set('t3',R?usd(v.g):'');set('t3l',gl(R));set('t4',usd(v.tot));dates(s);set('v3',usd(v.tot));set('v4',usd(r2(o+num(get(s,'prev'))+v.tot)));const e=$('#i-orig');if(e)e.placeholder=usd(qt)}
function rc(){const s='Rate Calculator',need=num(get(s,'wage'))+num(get(s,'costs')),hy=num(get(s,'weeks'))*num(get(s,'hrs')),rt=hy>0?r2(need/hy):0;
 set('c-need',usd(need));set('c-hy',hy.toLocaleString('en-AU'));set('rt',usd(rt));set('c-rg',usd(reg()?r2(rt*(1+rate())):rt));
 const p=num(get(s,'part')),sp=r2(p*(1+num(get(s,'mk'))/100)),pf=r2(sp-p);set('c-sp',usd(sp));set('c-pf',usd(pf));set('c-mg',(sp>0?pf/sp*100:0).toFixed(1)+'%')}
function calc(){if(tab==='Variation')vc();else if(tab==='Rate Calculator')rc();else if($('#c-pay1'))dc()}

/* ---------- wiring ---------- */
const mf=e=>{if(e.classList.contains('m')&&has(e.value))e.value=usd(num(e.value))};
function fill(){$$('[data-k]').forEach(e=>{const v=get(e.dataset.s,e.dataset.k);if(v!=null)e.value=v;else if(e.tagName==='SELECT'&&e.dataset.s!=='D')e.value='Yes';mf(e);if(e.tagName==='TEXTAREA')grow(e)})}
const grow=e=>{e.style.height='auto';e.style.height=e.scrollHeight+'px'};
const setList=()=>{$('#dl').innerHTML=LISTS[ST.D.trade].split('|').map(x=>`<option value="${esc(x)}">`).join('')};
function go(t){tab=t;$('#nav').innerHTML=TABS.map(x=>`<button role="tab" aria-selected="${x===t}" data-t="${x}">${x}</button>`).join('');$('#m').innerHTML=view();fill();calc();setList();scrollTo(0,0)}
$('#nav').onclick=e=>{const b=e.target.closest('button');if(b)go(b.dataset.t)};
document.addEventListener('input',e=>{const t=e.target;if(!t.dataset.k)return;put(t.dataset.s,t.dataset.k,t.value);if(t.tagName==='TEXTAREA')grow(t);if(t.dataset.k==='trade')setList();calc()});
document.addEventListener('change',e=>{const t=e.target;if(!t.dataset.k)return;if(t.dataset.k==='trade')setList();calc()});
document.addEventListener('focusin',e=>{const t=e.target;if(t.classList&&t.classList.contains('m')&&has(t.value)){t.value=num(t.value)||'';t.select&&t.select()}});
document.addEventListener('focusout',e=>{const t=e.target;if(t.classList&&t.classList.contains('m')){put(t.dataset.s,t.dataset.k,t.value);mf(t);put(t.dataset.s,t.dataset.k,t.value);calc()}});
document.addEventListener('click',e=>{const t=e.target;
 if(t.id==='pdf'){const o=document.title;document.title=`${tab} ${get(tab,'no')||''} ${ST.D.name||''}`.trim();window.print();document.title=o}
 if(t.id==='clr'&&confirm('Clear this document? Your business details stay.')){ST.T[tab]={};save();go(tab)}});
go('Start Here');
